---
title: "Two ways to include people into ecological systems"
---

Human activities are a primary driver of patterns of biodiversity and ecosystem processes across the globe (Ellis;). Tremendous work already illustrates how human activities drive ecosystem processes, from global climate models, habitat destruction, biomagnification, microplastics and PFAS, to endangered species recovery, to name just a few. However, we rarely connect these ecological phenomena back to the one human process that governs them: politics. In this article, I show how we can paradoxically avoid cultural baggage by explicitly including politics in models of ecosystem processes.  

Models are useful abstractions of how the world works. In addition to reducing ambiguity, and illuminating causal relationships, they help objectify and de-personalize a contentious problem. It may be able to take a problem out of interpersonal relationships and into a space that parties can hold at arms' length and examine more objectively. 

Consider a simple model of the carbon cycle. 








