<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>14&nbsp; ForestGEO Community Ecology: Why are there so many tree species, and where? – Basic Ecological Concepts and Data in R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./13-diversity-gbif.html" rel="next">
<link href="./11-predator-prey-Claude.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-89ca6ca939e49a4038144f8f28e82152.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-J0R6F7XN66"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-J0R6F7XN66', { 'anonymize_ip': true});
</script>
<style>
h1, h2, h3, h4, h5, h6,
.title, .quarto-title-block .title, .chapter-title {
  font-family: serif;
}
</style>


</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./13-diversity-forestgeo.html"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">ForestGEO Community Ecology: Why are there so many tree species, and where?</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Basic Ecological Concepts and Data in R</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-AI-v4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">AI and the Changing Landscape of Skills in Ecology</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-computer-setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Computer setup and first R script</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./thinking.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Thinking about thinking about concepts</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-trees_and_people.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Environmental Justice: How income relates to environment.</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-global_temp_anomalies_v2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Physical Environment: A Fate of Earth</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./traits-physiology.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Traits, Physiology, and the Global Spectrum of Plant Form and Function</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-extrapair_copulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Behavior: Extra-pair copulation in a monogamous species</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-DI-pop-growth-Claude.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Density-independent Population Growth: Humans on the rise</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-structured-pop-growth_v2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Structured demography: How a graduate student helped save the loggerhead sea turtle</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-density-dep-pop-growth-Claude.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Density-dependence in population growth</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-direct-interactions-Claude.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Direct species interactions: understanding mechanisms of invasion in mosquitoes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-mutualisms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Mutualisms: Do ants protect pea plants?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-predator-prey-Claude.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Of wolves and moose, on Isle Royale</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-diversity-forestgeo.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">ForestGEO Community Ecology: Why are there so many tree species, and where?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-diversity-gbif.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">GBIF: Why are there so many species, and where?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-metabolic-ecology_v_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Metabolic Ecology: How do body size and temperature affect nutrient cycling?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-ecosystem-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">An Introduction to the Carbon Cycle and Global Heating</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./funding-science.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Funding Ecological and Environmental Science: Following the Money</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./career-skills-crosswalk.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">From This Book to Your Résumé: A Skills Crosswalk</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#goals" id="toc-goals" class="nav-link active" data-scroll-target="#goals"><span class="header-section-number">14.1</span> Goals</a></li>
  <li><a href="#preparatory-steps" id="toc-preparatory-steps" class="nav-link" data-scroll-target="#preparatory-steps"><span class="header-section-number">14.2</span> Preparatory Steps</a></li>
  <li><a href="#background" id="toc-background" class="nav-link" data-scroll-target="#background"><span class="header-section-number">14.3</span> Background</a>
  <ul class="collapse">
  <li><a href="#three-things-people-mean-by-diversity" id="toc-three-things-people-mean-by-diversity" class="nav-link" data-scroll-target="#three-things-people-mean-by-diversity"><span class="header-section-number">14.3.1</span> Three things people mean by “diversity”</a></li>
  <li><a href="#richness-depends-on-how-hard-you-looked" id="toc-richness-depends-on-how-hard-you-looked" class="nav-link" data-scroll-target="#richness-depends-on-how-hard-you-looked"><span class="header-section-number">14.3.2</span> Richness depends on how hard you looked</a></li>
  <li><a href="#the-latitudinal-diversity-gradientand-an-exception" id="toc-the-latitudinal-diversity-gradientand-an-exception" class="nav-link" data-scroll-target="#the-latitudinal-diversity-gradientand-an-exception"><span class="header-section-number">14.3.3</span> The latitudinal diversity gradient—and an exception</a></li>
  </ul></li>
  <li><a href="#hypotheses-and-predictions" id="toc-hypotheses-and-predictions" class="nav-link" data-scroll-target="#hypotheses-and-predictions"><span class="header-section-number">14.4</span> Hypotheses and Predictions</a></li>
  <li><a href="#get-r-ready-for-work" id="toc-get-r-ready-for-work" class="nav-link" data-scroll-target="#get-r-ready-for-work"><span class="header-section-number">14.5</span> Get R ready for work</a></li>
  <li><a href="#measuring-diversity-at-bci" id="toc-measuring-diversity-at-bci" class="nav-link" data-scroll-target="#measuring-diversity-at-bci"><span class="header-section-number">14.6</span> Measuring diversity at BCI</a>
  <ul class="collapse">
  <li><a href="#richness-plot-by-plot" id="toc-richness-plot-by-plot" class="nav-link" data-scroll-target="#richness-plot-by-plot"><span class="header-section-number">14.6.1</span> Richness, plot by plot</a></li>
  <li><a href="#evenness-and-the-rankabundance-curve" id="toc-evenness-and-the-rankabundance-curve" class="nav-link" data-scroll-target="#evenness-and-the-rankabundance-curve"><span class="header-section-number">14.6.2</span> Evenness and the rank–abundance curve</a></li>
  <li><a href="#one-number-shannon-and-simpson-diversity" id="toc-one-number-shannon-and-simpson-diversity" class="nav-link" data-scroll-target="#one-number-shannon-and-simpson-diversity"><span class="header-section-number">14.6.3</span> One number: Shannon and Simpson diversity</a></li>
  <li><a href="#rarefaction-comparing-fairly" id="toc-rarefaction-comparing-fairly" class="nav-link" data-scroll-target="#rarefaction-comparing-fairly"><span class="header-section-number">14.6.4</span> Rarefaction: comparing fairly</a></li>
  <li><a href="#does-richness-just-track-the-number-of-stems" id="toc-does-richness-just-track-the-number-of-stems" class="nav-link" data-scroll-target="#does-richness-just-track-the-number-of-stems"><span class="header-section-number">14.6.5</span> Does richness just track the number of stems?</a></li>
  </ul></li>
  <li><a href="#comparing-forests-across-the-globe" id="toc-comparing-forests-across-the-globe" class="nav-link" data-scroll-target="#comparing-forests-across-the-globe"><span class="header-section-number">14.7</span> Comparing forests across the globe</a></li>
  <li><a href="#sec-deliverables-diversity" id="toc-sec-deliverables-diversity" class="nav-link" data-scroll-target="#sec-deliverables-diversity"><span class="header-section-number">14.8</span> Deliverables</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">14.9</span> References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">ForestGEO Community Ecology: Why are there so many tree species, and where?</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<!-- Suggested opening figure: a canopy or map of the ForestGEO network. e.g. ![A ForestGEO forest dynamics plot.](figs/forestgeo_canopy.png) -->
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>If you haven’t met these before:</strong> this chapter uses ideas about counting and comparing populations from the population-growth chapters (a <em>count</em> of stems is just population size), and the log-transformation logic from the metabolic ecology chapter (<a href="15-metabolic-ecology_v_2.html" class="quarto-xref"><span>Chapter 16</span></a>). You can do this chapter without having finished those, but a glance back will help.</p>
</div>
</div>
</div>
<section id="goals" class="level2" data-number="14.1">
<h2 data-number="14.1" class="anchored" data-anchor-id="goals"><span class="header-section-number">14.1</span> Goals</h2>
<ul>
<li>Evaluate the consistency of the latitudinal gradient of species diversity.</li>
<li>Define species richness, evenness, and diversity, and explain why these are three different things.</li>
<li>Use a real forest-census data set to measure diversity, and to see why the number you get depends on how hard you looked.</li>
<li>Develop and evaluate a prediction about how forest diversity changes from the poles to the equator, and confront a real exception to that pattern.</li>
<li>Practice reading the <em>shape</em> of an ecological relationship (rank–abundance and species–accumulation curves) before trusting a single summary number.</li>
</ul>
<p><em>Time: ~2–3 h. Most students start the activity in one 80-minute class period and finish the deliverables at home.</em></p>
</section>
<section id="preparatory-steps" class="level2" data-number="14.2">
<h2 data-number="14.2" class="anchored" data-anchor-id="preparatory-steps"><span class="header-section-number">14.2</span> Preparatory Steps</h2>
<ol type="1">
<li>Find out what you need for the deliverables (<a href="13-diversity-gbif.html#sec-deliverables-diversity" class="quarto-xref"><span>Section 15.9</span></a>) <strong>before</strong> you start, including the parts you will sketch by hand and turn in.</li>
<li>Watch the video lectures on biodiversity and the latitudinal diversity gradient.</li>
<li>Skim <span class="citation" data-cites="davies2021">(<a href="references.html#ref-davies2021" role="doc-biblioref"><strong>davies2021?</strong></a>)</span> for one paragraph on what the ForestGEO network is. You do not need the details—just the idea that many forests around the world have been censused <em>the same way</em>.</li>
<li>Install the <code>vegan</code> package once (instructions below). Everything else uses packages you already have.</li>
</ol>
</section>
<section id="background" class="level2" data-number="14.3">
<h2 data-number="14.3" class="anchored" data-anchor-id="background"><span class="header-section-number">14.3</span> Background</h2>
<p>Walk into a forest in Ohio and you might learn most of the trees in an afternoon: a few oaks, some maples, hickory, beech, ash. Walk into a lowland forest in Panama or Malaysia and you could spend a career and not finish. Why the enormous difference? And how would you even <em>measure</em> it fairly, when one forest hands you twenty species and another hands you eight hundred?</p>
<p>To compare forests honestly, ecologists needed forests measured the same way. That is exactly what the <strong>Forest Global Earth Observatory (ForestGEO)</strong> provides. Beginning with a single 50-hectare plot on Barro Colorado Island (BCI) in Panama in 1980, the network has grown to dozens of large forest dynamics plots spread across the world’s major forests <span class="citation" data-cites="davies2021">(<a href="references.html#ref-davies2021" role="doc-biblioref"><strong>davies2021?</strong></a>)</span>. In every plot, field crews follow the same protocol: every free-standing woody stem at least 1 cm in diameter is mapped, tagged, identified to species, and then <em>re-measured</em> every five years or so <span class="citation" data-cites="anderson-teixeira2015">(<a href="references.html#ref-anderson-teixeira2015" role="doc-biblioref"><strong>anderson-teixeira2015?</strong></a>)</span>. A single 50-ha plot can hold a few hundred thousand individual trees. Because the protocol is identical across continents, a difference in the numbers reflects a difference in the <em>forests</em>, not a difference in the <em>method</em>.</p>
<section id="three-things-people-mean-by-diversity" class="level3" data-number="14.3.1">
<h3 data-number="14.3.1" class="anchored" data-anchor-id="three-things-people-mean-by-diversity"><span class="header-section-number">14.3.1</span> Three things people mean by “diversity”</h3>
<p>“Diversity” is used loosely in conversation, but it bundles together at least three distinct ideas, and confusing them is one of the most common mistakes in ecology.</p>
<ul>
<li><strong>Richness</strong> is simply the <em>number</em> of species present. It ignores how common each one is. A forest with 100 species, 99 of them represented by a single tree, has the same richness as a forest with 100 evenly abundant species.</li>
<li><strong>Evenness</strong> describes how equally the individuals are spread among the species. The two forests just described have very different evenness.</li>
<li><strong>Diversity</strong> indices (Shannon, Simpson, and others) combine richness and evenness into one number, so that a community is “more diverse” both when it has more species <em>and</em> when those species are more evenly abundant.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Follow the Logic: why richness alone can fool you
</div>
</div>
<div class="callout-body-container callout-body">
<p>Imagine two 1-hectare plots. Plot A has 10 species, each with 100 trees. Plot B has 10 species, but one species has 991 trees and the other nine have one tree each. Both have richness = 10. Yet if you walked through Plot B blindfolded and grabbed trees at random, you would almost always grab the same species—it <em>behaves</em> like a one-species forest. Richness counts the rare species as fully as the common ones; evenness and diversity indices do not. Before you compute a diversity index, ask yourself which of these three quantities your question is really about.</p>
</div>
</div>
</section>
<section id="richness-depends-on-how-hard-you-looked" class="level3" data-number="14.3.2">
<h3 data-number="14.3.2" class="anchored" data-anchor-id="richness-depends-on-how-hard-you-looked"><span class="header-section-number">14.3.2</span> Richness depends on how hard you looked</h3>
<p>Here is the uncomfortable part. Richness is not a fixed property you can read off a forest like its temperature. The more individuals you count, the more species you find, because rare species only show up once you have sampled enough trees to stumble onto them. Census 1 hectare at BCI and you find about 168 tree species; census all 50 hectares and you find roughly 300 <span class="citation" data-cites="condit1996">(<a href="references.html#ref-condit1996" role="doc-biblioref"><strong>condit1996?</strong></a>)</span>. The forest did not change—your <em>sample</em> got bigger.</p>
<p>This is the <strong>species–accumulation</strong> (or species–area) relationship, and it means two numbers are only comparable if they come from the same amount of effort. Comparing “168 species” from a 1-ha plot to “493 species” from a 50-ha plot tells you almost nothing, because the second number had fifty times the chance to find rarities. Ecologists handle this with <strong>rarefaction</strong>: ask how many species you would <em>expect</em> if every sample were thinned to the same number of individuals <span class="citation" data-cites="gotelli2001">(<a href="references.html#ref-gotelli2001" role="doc-biblioref"><strong>gotelli2001?</strong></a>)</span>. You will do this below.</p>
</section>
<section id="the-latitudinal-diversity-gradientand-an-exception" class="level3" data-number="14.3.3">
<h3 data-number="14.3.3" class="anchored" data-anchor-id="the-latitudinal-diversity-gradientand-an-exception"><span class="header-section-number">14.3.3</span> The latitudinal diversity gradient—and an exception</h3>
<p>Across most groups of organisms, diversity rises as you move from the poles toward the equator <span class="citation" data-cites="hillebrand2004">(<a href="references.html#ref-hillebrand2004" role="doc-biblioref"><strong>hillebrand2004?</strong></a>)</span>. Tropical forests are the headline example. But the tropics are not uniform. Compared per hectare, lowland forests in the Neotropics and Southeast Asia are staggeringly rich, while African rainforests are consistently <em>less</em> rich—a pattern old enough that ecologists once called Africa “the odd man out” <span class="citation" data-cites="kenfack2007">(<a href="references.html#ref-kenfack2007" role="doc-biblioref"><strong>kenfack2007?</strong></a>)</span>. The 50-ha plot at Korup in Cameroon holds about 493 tree species among more than 329,000 individuals—extraordinary by temperate standards, yet well below comparable Asian and Neotropical plots censused the same way <span class="citation" data-cites="kenfack2007">(<a href="references.html#ref-kenfack2007" role="doc-biblioref"><strong>kenfack2007?</strong></a>)</span>. A good theory of diversity has to explain both the broad gradient <em>and</em> its exceptions.</p>
</section>
</section>
<section id="hypotheses-and-predictions" class="level2" data-number="14.4">
<h2 data-number="14.4" class="anchored" data-anchor-id="hypotheses-and-predictions"><span class="header-section-number">14.4</span> Hypotheses and Predictions</h2>
<p>We will pursue two questions, each with its own logic.</p>
<p><strong>Question 1 (within one forest):</strong> How is diversity structured at BCI—are species roughly equal in abundance, or are a few common and most rare?</p>
<p>This is an <strong>inductive</strong> question: we will let a large, carefully collected data set reveal a pattern, rather than deducing the pattern from a model first.</p>
<p><strong>Question 2 (across forests):</strong> How does tree richness change with latitude across the ForestGEO network?</p>
<p>This one is <strong>deductive</strong>: the latitudinal-gradient hypothesis makes a clear, testable prediction <em>before</em> we look at the data—richness should decline as we move away from the equator. When we meet the African exception, we will switch to <strong>abductive</strong> reasoning: given a surprising observation, what is the best explanation?</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Predict before you compute
</div>
</div>
<div class="callout-body-container callout-body">
<p>Before you run a single line of code, sketch three graphs by hand on paper and photograph them for your deliverables:</p>
<ol type="1">
<li><strong>Rank–abundance.</strong> Put species <em>rank</em> (most abundant = 1) on the x-axis and <em>abundance</em> on the y-axis. Draw the shape you expect for a tropical forest.</li>
<li><strong>Species accumulation.</strong> Put <em>number of hectares sampled</em> on the x-axis and <em>cumulative species found</em> on the y-axis. Draw the shape you expect, and mark whether you think it ever flattens out.</li>
<li><strong>Richness vs.&nbsp;latitude.</strong> Put <em>absolute latitude</em> on the x-axis and <em>species richness</em> on the y-axis. Draw the line the latitudinal-gradient hypothesis predicts.</li>
</ol>
<p>Keep these. The point of the chapter is to compare your hand-drawn predictions to what the data actually do—and to be able to <em>explain</em> any mismatch.</p>
</div>
</div>
</section>
<section id="get-r-ready-for-work" class="level2" data-number="14.5">
<h2 data-number="14.5" class="anchored" data-anchor-id="get-r-ready-for-work"><span class="header-section-number">14.5</span> Get R ready for work</h2>
<p>We use the <code>vegan</code> package, the standard toolkit for community ecology in R, together with the tidyverse and <code>broom</code>. <code>vegan</code> ships with the <strong>BCI</strong> data set: counts of tree species in fifty 1-hectare plots from the Barro Colorado Island census—real data, already in R, so nothing can break or go offline.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Run this ONCE, then comment it out.</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"vegan"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vegan)      <span class="co"># community ecology: diversity, rarefaction, accumulation</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)  <span class="co"># data wrangling and ggplot2</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)      <span class="co"># tidy model output</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(BCI)           <span class="co"># load the Barro Colorado Island plot-by-species table</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(BCI)            <span class="co"># rows = 1-ha plots, columns = species</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  50 225</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>BCI[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>]       <span class="co"># a corner of the table: counts of trees, by species, by plot</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Abarema.macradenia Vachellia.melanoceras Acalypha.diversifolia
1                  0                     0                     0
2                  0                     0                     0
3                  0                     0                     0
4                  0                     0                     0
5                  0                     0                     0
  Acalypha.macrostachya Adelia.triloba Aegiphila.panamensis
1                     0              0                    0
2                     0              0                    0
3                     0              0                    0
4                     0              3                    0
5                     0              1                    1</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Walk me through this data table
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Each <strong>row</strong> is one 1-hectare plot (there are 50). Each <strong>column</strong> is one tree species (there are 225 in this curated subset). Each <strong>cell</strong> is the <em>number of individual trees</em> of that species counted in that plot. A community data table in this “sites-by-species” layout is the workhorse of community ecology—almost everything below is just a clever summary of these counts. If you understand that one cell is “how many trees of species <em>j</em> I found in plot <em>i</em>,” you understand the whole table.</p>
</div>
</div>
</div>
</section>
<section id="measuring-diversity-at-bci" class="level2" data-number="14.6">
<h2 data-number="14.6" class="anchored" data-anchor-id="measuring-diversity-at-bci"><span class="header-section-number">14.6</span> Measuring diversity at BCI</h2>
<section id="richness-plot-by-plot" class="level3" data-number="14.6.1">
<h3 data-number="14.6.1" class="anchored" data-anchor-id="richness-plot-by-plot"><span class="header-section-number">14.6.1</span> Richness, plot by plot</h3>
<p><code>specnumber()</code> counts the species present (abundance &gt; 0) in each plot.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>richness <span class="ot">&lt;-</span> <span class="fu">specnumber</span>(BCI)     <span class="co"># one richness value per 1-ha plot</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(richness)               <span class="co"># how many species per hectare?</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  77.00   86.00   91.00   90.78   94.00  109.00 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(<span class="at">richness =</span> richness) <span class="sc">|&gt;</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> richness)) <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>, <span class="at">fill =</span> <span class="st">"forestgreen"</span>, <span class="at">colour =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Species per 1-ha plot"</span>, <span class="at">y =</span> <span class="st">"Number of plots"</span>) <span class="sc">+</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-richness-hist" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-richness-hist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="13-diversity-forestgeo_files/figure-html/fig-richness-hist-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-richness-hist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.1: Distribution of tree species richness across the fifty 1-ha BCI plots.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Notice that even within a single 50-ha forest, 1-ha richness varies from plot to plot. Diversity is patchy at small scales.</p>
</section>
<section id="evenness-and-the-rankabundance-curve" class="level3" data-number="14.6.2">
<h3 data-number="14.6.2" class="anchored" data-anchor-id="evenness-and-the-rankabundance-curve"><span class="header-section-number">14.6.2</span> Evenness and the rank–abundance curve</h3>
<p>To <em>see</em> evenness, pool all 50 plots, sort species from most to least abundant, and plot abundance against rank. This is a <strong>Whittaker (rank–abundance) plot</strong>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>pooled <span class="ot">&lt;-</span> <span class="fu">colSums</span>(BCI)                      <span class="co"># total trees of each species, all plots</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>rank_ab <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">species =</span> <span class="fu">names</span>(pooled), <span class="at">abundance =</span> pooled) <span class="sc">|&gt;</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(abundance <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">|&gt;</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(abundance)) <span class="sc">|&gt;</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">rank =</span> <span class="fu">row_number</span>())</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(rank_ab, <span class="fu">aes</span>(<span class="at">x =</span> rank, <span class="at">y =</span> abundance)) <span class="sc">+</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">colour =</span> <span class="st">"grey40"</span>) <span class="sc">+</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_log10</span>() <span class="sc">+</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Species rank (1 = most abundant)"</span>,</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Total abundance (log scale)"</span>) <span class="sc">+</span></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-rankabundance" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rankabundance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="13-diversity-forestgeo_files/figure-html/fig-rankabundance-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rankabundance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.2: Rank–abundance (Whittaker) plot for pooled BCI trees. A few species are very common; a long tail is rare.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Follow the Logic: why a log scale, and why the long tail matters
</div>
</div>
<div class="callout-body-container callout-body">
<p>On a log y-axis, a straight-ish declining line means abundance falls by a roughly <em>constant factor</em> with each step down the ranking—the 10th species is some fixed fraction of the 1st, the 100th a fixed fraction of the 10th. The long, flat tail on the right is the army of <strong>rare</strong> species, each with only a handful of individuals. That tail is the reason richness keeps climbing as you sample more, and the reason a single common-species walk through the forest gives a badly biased impression of diversity. Compare this real curve to the one you drew by hand.</p>
</div>
</div>
</section>
<section id="one-number-shannon-and-simpson-diversity" class="level3" data-number="14.6.3">
<h3 data-number="14.6.3" class="anchored" data-anchor-id="one-number-shannon-and-simpson-diversity"><span class="header-section-number">14.6.3</span> One number: Shannon and Simpson diversity</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>shannon <span class="ot">&lt;-</span> <span class="fu">diversity</span>(BCI, <span class="at">index =</span> <span class="st">"shannon"</span>)   <span class="co"># accounts for richness + evenness</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>simpson <span class="ot">&lt;-</span> <span class="fu">diversity</span>(BCI, <span class="at">index =</span> <span class="st">"simpson"</span>)   <span class="co"># prob. two random trees differ</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(<span class="at">shannon =</span> shannon, <span class="at">simpson =</span> simpson) <span class="sc">|&gt;</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="fu">list</span>(<span class="at">mean =</span> mean, <span class="at">sd =</span> sd)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  shannon_mean shannon_sd simpson_mean simpson_sd
         &lt;dbl&gt;      &lt;dbl&gt;        &lt;dbl&gt;      &lt;dbl&gt;
1         3.82      0.234        0.959     0.0257</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="do">## The "effective number of species": how many EQUALLY-common species</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="do">## would give the same Shannon diversity?</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>effective_species <span class="ot">&lt;-</span> <span class="fu">exp</span>(shannon)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(effective_species)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  14.04   42.27   46.99   46.66   52.94   58.99 </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Follow the Logic: what <code>exp(H)</code> means
</div>
</div>
<div class="callout-body-container callout-body">
<p>Shannon’s <em>H</em> is in awkward units (it’s an entropy). Exponentiating it converts <em>H</em> into an <strong>effective number of species</strong>: the number of <em>equally abundant</em> species that would produce the diversity you observed. If a plot has 90 real species but <code>exp(H)</code> is only 35, that is the data telling you “this forest <em>behaves</em> like 35 evenly common species, because the other ~55 are rare.” That single translation—from an abstract index back into ‘number of species’—is why effective numbers are now preferred over raw indices.</p>
</div>
</div>
</section>
<section id="rarefaction-comparing-fairly" class="level3" data-number="14.6.4">
<h3 data-number="14.6.4" class="anchored" data-anchor-id="rarefaction-comparing-fairly"><span class="header-section-number">14.6.4</span> Rarefaction: comparing fairly</h3>
<p>Plots differ in how many trees they contain, so a plot with more stems gets more chances to accumulate species. Rarefaction asks: at a <em>common</em> number of individuals, how many species would we expect?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>stems <span class="ot">&lt;-</span> <span class="fu">rowSums</span>(BCI)                 <span class="co"># total trees per plot</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>min_stems <span class="ot">&lt;-</span> <span class="fu">min</span>(stems)               <span class="co"># thin every plot to this many</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>rarefied <span class="ot">&lt;-</span> <span class="fu">rarefy</span>(BCI, <span class="at">sample =</span> min_stems)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(<span class="at">observed =</span> richness, <span class="at">rarefied =</span> rarefied) <span class="sc">|&gt;</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_observed =</span> <span class="fu">mean</span>(observed),</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">mean_rarefied =</span> <span class="fu">mean</span>(rarefied))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  mean_observed mean_rarefied
          &lt;dbl&gt;         &lt;dbl&gt;
1          90.8          83.0</code></pre>
</div>
</div>
<p>Why does the rarefied richness come out lower than the observed richness? Make sure you can answer that in your own words before moving on—it is the whole reason rarefaction exists.</p>
</section>
<section id="does-richness-just-track-the-number-of-stems" class="level3" data-number="14.6.5">
<h3 data-number="14.6.5" class="anchored" data-anchor-id="does-richness-just-track-the-number-of-stems"><span class="header-section-number">14.6.5</span> Does richness just track the number of stems?</h3>
<p>If richer plots are simply the ones with more trees, that is worth knowing. We can fit a quick linear model and read it with <code>broom</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>model_df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">richness =</span> richness, <span class="at">stems =</span> <span class="fu">rowSums</span>(BCI))</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(richness <span class="sc">~</span> stems, <span class="at">data =</span> model_df)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(fit)      <span class="co"># slope, intercept, and their uncertainty</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term        estimate std.error statistic  p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept) 91.9       10.2        8.97  7.85e-12
2 stems       -0.00260    0.0238    -0.109 9.13e- 1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(fit)    <span class="co"># r.squared: how much of richness variation stems explain</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1  0.000249       -0.0206  7.08    0.0120   0.913     1  -168.  342.  347.
# ℹ 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(model_df, <span class="fu">aes</span>(<span class="at">x =</span> stems, <span class="at">y =</span> richness)) <span class="sc">+</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">colour =</span> <span class="st">"darkorange"</span>) <span class="sc">+</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Stems per 1-ha plot"</span>, <span class="at">y =</span> <span class="st">"Species per 1-ha plot"</span>) <span class="sc">+</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-richness-stems" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-richness-stems-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="13-diversity-forestgeo_files/figure-html/fig-richness-stems-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-richness-stems-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.3: Plot-level richness vs.&nbsp;number of stems, with a fitted line.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Walk me through <code>tidy()</code> and <code>glance()</code>
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><code>lm()</code> fits the line. Instead of reading the dense default <code>summary()</code>, <code>broom</code> gives us two tidy tables. <code>tidy(fit)</code> returns one row per coefficient—the slope tells you how many extra species you get per additional stem, and its <code>p.value</code> tells you whether that slope is distinguishable from zero. <code>glance(fit)</code> returns one row for the whole model; the key column is <code>r.squared</code>, the fraction of plot-to-plot richness variation explained by stem number. If <code>r.squared</code> is low, then richness is <em>not</em> just a stem-count artifact—something ecological is going on.</p>
</div>
</div>
</div>
</section>
</section>
<section id="comparing-forests-across-the-globe" class="level2" data-number="14.7">
<h2 data-number="14.7" class="anchored" data-anchor-id="comparing-forests-across-the-globe"><span class="header-section-number">14.7</span> Comparing forests across the globe</h2>
<p>Now the cross-continental question. Below is a small table of ForestGEO (and sister) plots, with the species richness reported for each and the plot area it came from. The numbers are drawn from the published site descriptions and papers cited at the end of the chapter.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>sites <span class="ot">&lt;-</span> <span class="fu">tribble</span>(</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span>site,             <span class="sc">~</span>country,    <span class="sc">~</span>continent,      <span class="sc">~</span>abs_latitude, <span class="sc">~</span>area_ha, <span class="sc">~</span>species,</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"SCBI"</span>,            <span class="st">"USA"</span>,       <span class="st">"North America"</span>,          <span class="fl">38.9</span>,     <span class="fl">25.6</span>,       <span class="dv">65</span>,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"BCI"</span>,             <span class="st">"Panama"</span>,    <span class="st">"Neotropics"</span>,              <span class="fl">9.2</span>,     <span class="fl">50.0</span>,      <span class="dv">300</span>,</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Korup"</span>,           <span class="st">"Cameroon"</span>,  <span class="st">"Africa"</span>,                  <span class="fl">5.1</span>,     <span class="fl">50.0</span>,      <span class="dv">493</span>,</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Pasoh"</span>,           <span class="st">"Malaysia"</span>,  <span class="st">"Asia"</span>,                    <span class="fl">3.0</span>,     <span class="fl">50.0</span>,      <span class="dv">800</span>,</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Yasuni"</span>,          <span class="st">"Ecuador"</span>,   <span class="st">"Neotropics"</span>,              <span class="fl">0.7</span>,     <span class="fl">50.0</span>,     <span class="dv">1150</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>sites</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 6
  site   country  continent     abs_latitude area_ha species
  &lt;chr&gt;  &lt;chr&gt;    &lt;chr&gt;                &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
1 SCBI   USA      North America         38.9    25.6      65
2 BCI    Panama   Neotropics             9.2    50       300
3 Korup  Cameroon Africa                 5.1    50       493
4 Pasoh  Malaysia Asia                   3      50       800
5 Yasuni Ecuador  Neotropics             0.7    50      1150</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>A trap built into this table
</div>
</div>
<div class="callout-body-container callout-body">
<p>These richness numbers come from <strong>different plot areas</strong> (25.6 ha vs.&nbsp;50 ha). You just spent half a chapter learning that richness depends on sampling effort. So before you compare these numbers, ask: is it fair to compare a 25.6-ha count to a 50-ha count? For the cleanest comparison, ecologists use <em>1-hectare</em> richness, where the published values are roughly: BCI <strong>168</strong>, Pasoh <strong>497</strong>, Yasuni <strong>670</strong> species per hectare <span class="citation" data-cites="condit1996">(<a href="references.html#ref-condit1996" role="doc-biblioref"><strong>condit1996?</strong></a>)</span>. Carry that caveat into every conclusion you draw below.</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sites, <span class="fu">aes</span>(<span class="at">x =</span> abs_latitude, <span class="at">y =</span> species,</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">colour =</span> continent, <span class="at">size =</span> area_ha)) <span class="sc">+</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> site), <span class="at">vjust =</span> <span class="sc">-</span><span class="dv">1</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Absolute latitude (degrees from equator)"</span>,</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Species richness (in plot)"</span>,</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">colour =</span> <span class="st">"Continent"</span>, <span class="at">size =</span> <span class="st">"Plot area (ha)"</span>) <span class="sc">+</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="co"># + scale_y_log10()</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-latitude" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-latitude-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="13-diversity-forestgeo_files/figure-html/fig-latitude-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-latitude-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.4: Tree species richness vs.&nbsp;absolute latitude across forest plots. Point size shows plot area; colour shows continent. Mind the area caveat.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Two things should jump out. First, the broad <strong>latitudinal gradient</strong>: the temperate plot (SCBI, Virginia) has a tiny fraction of the richness of the tropical plots—exactly what the hypothesis predicted, and, ideally, what you drew by hand. Second, the <strong>exception</strong>: among the tropical plots, the African site (Korup) is clearly less rich than the Asian and Neotropical sites, even after accounting for area. The gradient is real, but it is not the whole story.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Follow the Logic: from deduction to abduction
</div>
</div>
<div class="callout-body-container callout-body">
<p>The latitudinal-gradient hypothesis <em>deduced</em> a prediction (richness falls with latitude) and the data largely confirmed it. But Korup is a surprise the hypothesis did not predict. Now you reason <strong>abductively</strong>: what is the best explanation for a depauperate African tropics? Candidate explanations in the literature include a drier, more variable climate history (Pleistocene contractions of African rainforest), a smaller total area of lowland tropical forest on the continent, and higher past extinction. You do not have to settle this—you have to recognize that a good observation generates the <em>next</em> hypothesis, and to be able to say what data would help you choose among these explanations.</p>
</div>
</div>
</section>
<section id="sec-deliverables-diversity" class="level2" data-number="14.8">
<h2 data-number="14.8" class="anchored" data-anchor-id="sec-deliverables-diversity"><span class="header-section-number">14.8</span> Deliverables</h2>
<p>Assemble the following into a single document and submit it online.</p>
<ol type="1">
<li><p><strong>Your three hand-drawn predictions</strong> (rank–abundance, species accumulation, richness vs.&nbsp;latitude), photographed, <em>before</em> you ran any code.</p></li>
<li><p><strong>In your own words (2–3 sentences each):</strong> a. the difference between richness, evenness, and diversity; b. why rarefied richness came out lower than observed richness; c.&nbsp;what <code>exp(H)</code> (effective number of species) tells you that raw Shannon <em>H</em> does not.</p></li>
<li><p><strong>Reproduce and include</strong> the rank–abundance plot (<a href="#fig-rankabundance" class="quarto-xref">Figure&nbsp;<span>14.2</span></a>) and the global latitude plot (<a href="#fig-latitude" class="quarto-xref">Figure&nbsp;<span>14.4</span></a>). For each, write one sentence comparing the real figure to your hand-drawn prediction. Where they differ, explain <em>why</em>—this is the point of the assignment.</p></li>
<li><p><strong>Build a species–accumulation curve</strong> for BCI and include it. Starter code:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>accum <span class="ot">&lt;-</span> <span class="fu">specaccum</span>(BCI)   <span class="co"># cumulative species as plots are added</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>accum_df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">plots =</span> accum<span class="sc">$</span>sites,</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">richness =</span> accum<span class="sc">$</span>richness,</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">sd =</span> accum<span class="sc">$</span>sd)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(accum_df, <span class="fu">aes</span>(<span class="at">x =</span> plots, <span class="at">y =</span> richness)) <span class="sc">+</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> richness <span class="sc">-</span> sd, <span class="at">ymax =</span> richness <span class="sc">+</span> sd),</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>              <span class="at">fill =</span> <span class="st">"grey80"</span>) <span class="sc">+</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Number of 1-ha plots sampled"</span>,</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Cumulative species found"</span>) <span class="sc">+</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div></li>
</ol>
<p>In one or two sentences, answer: does the curve flatten out by 50 hectares? What does your answer imply about how many tree species the <em>whole</em> forest contains versus how many appear in any one plot?</p>
<ol start="5" type="1">
<li><p><strong>The African exception.</strong> In a short paragraph, propose the explanation you find most convincing for why Korup is less rich than comparable Asian and Neotropical plots, and state one kind of data that would help test your explanation.</p></li>
<li><p><strong>Audit the machine.</strong> Below is a paragraph generated by an AI chatbot when asked to summarize this chapter. It sounds authoritative and is <em>mostly</em> right, but it contains at least one substantive ecological error. Find the error(s), quote the offending sentence, and correct it using what you learned:</p>
<blockquote class="blockquote">
<p><em>“Species richness is the most complete measure of biodiversity because it accounts for both how many species are present and how evenly abundant they are. Because the ForestGEO plots all use the same protocol, a forest’s richness is a fixed property, so the 493 species recorded at Korup can be compared directly to the 168 species recorded in a one-hectare plot at BCI. Diversity always increases smoothly toward the equator, with no exceptions.”</em></p>
</blockquote></li>
</ol>
<p>This is exactly the skill this whole book is built around: a machine can produce a fluent paragraph in seconds, and only someone who understands the mechanisms can catch where it is subtly—or badly—wrong.</p>
</section>
<section id="references" class="level2" data-number="14.9">
<h2 data-number="14.9" class="anchored" data-anchor-id="references"><span class="header-section-number">14.9</span> References</h2>
<!--
BibTeX entries to add to your .bib (verify keys against your Zotero export). Several of these are likely already in MyLibrary_zotero.bib.

@article{davies2021, title   = {{ForestGEO}: Understanding forest diversity and dynamics through a global observatory network}, author  = {Davies, Stuart J. and others}, journal = {Biological Conservation}, volume  = {253}, pages   = {108907}, year    = {2021}, doi     = {10.1016/j.biocon.2020.108907} }

@article{anderson-teixeira2015, title   = {{CTFS-ForestGEO}: a worldwide network monitoring forests in an era of global change}, author  = {Anderson-Teixeira, Kristina J. and others}, journal = {Global Change Biology}, volume  = {21}, number  = {2}, pages   = {528--549}, year    = {2015}, doi     = {10.1111/gcb.12712} }

@article{condit1996, title   = {Species-area and species-individual relationships for tropical trees: a comparison of three 50-ha plots}, author  = {Condit, Richard and Hubbell, Stephen P. and Lafrankie, James V. and Sukumar, Raman and Manokaran, N. and Foster, Robin B. and Ashton, Peter S.}, journal = {Journal of Ecology}, volume  = {84}, number  = {4}, pages   = {549--562}, year    = {1996}, doi     = {10.2307/2261477} }

@article{kenfack2007, title   = {Rarity and abundance in a diverse {African} forest}, author  = {Kenfack, David and Thomas, Duncan W. and Chuyong, George B. and Condit, Richard}, journal = {Biodiversity and Conservation}, volume  = {16}, number  = {7}, pages   = {2045--2074}, year    = {2007}, doi     = {10.1007/s10531-006-9065-2} }

@article{hillebrand2004, title   = {On the generality of the latitudinal diversity gradient}, author  = {Hillebrand, Helmut}, journal = {The American Naturalist}, volume  = {163}, number  = {2}, pages   = {192--211}, year    = {2004}, doi     = {10.1086/381004} }

@article{gotelli2001, title   = {Quantifying biodiversity: procedures and pitfalls in the measurement and comparison of species richness}, author  = {Gotelli, Nicholas J. and Colwell, Robert K.}, journal = {Ecology Letters}, volume  = {4}, number  = {4}, pages   = {379--391}, year    = {2001}, doi     = {10.1046/j.1461-0248.2001.00230.x} }

-->
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>This chapter cites <span class="citation" data-cites="davies2021">(<a href="references.html#ref-davies2021" role="doc-biblioref"><strong>davies2021?</strong></a>)</span>, <span class="citation" data-cites="anderson-teixeira2015">(<a href="references.html#ref-anderson-teixeira2015" role="doc-biblioref"><strong>anderson-teixeira2015?</strong></a>)</span>, <span class="citation" data-cites="condit1996">(<a href="references.html#ref-condit1996" role="doc-biblioref"><strong>condit1996?</strong></a>)</span>, <span class="citation" data-cites="kenfack2007">(<a href="references.html#ref-kenfack2007" role="doc-biblioref"><strong>kenfack2007?</strong></a>)</span>, <span class="citation" data-cites="hillebrand2004">(<a href="references.html#ref-hillebrand2004" role="doc-biblioref"><strong>hillebrand2004?</strong></a>)</span>, <span class="citation" data-cites="gotelli2001">(<a href="references.html#ref-gotelli2001" role="doc-biblioref"><strong>gotelli2001?</strong></a>)</span>, and the <code>vegan</code> package <span class="citation" data-cites="oksanen2026vce">(<a href="references.html#ref-oksanen2026vce" role="doc-biblioref"><strong>oksanen2026vce?</strong></a>)</span>. Full references appear in the book’s reference list once these keys are in your <code>.bib</code>.</p>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./11-predator-prey-Claude.html" class="pagination-link" aria-label="Of wolves and moose, on Isle Royale">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Of wolves and moose, on Isle Royale</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./13-diversity-gbif.html" class="pagination-link" aria-label="GBIF: Why are there so many species, and where?">
        <span class="nav-page-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">GBIF: Why are there so many species, and where?</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>